var items = {
    'Ocarina': 0,
    'Hero\'s bow': 0,
    'Fire arrow': 0,
    'Ice arrow': 0,
    'Light arrow': 0,
    'Bombs': 0,
    'Bombchu': 0,
    'Deku stick': 0,
    'Deku nut': 0,
    'Magic bean': 0,
    'Powder keg': 0,
    'Picto box': 0,
    'Lens of truth': 0,
    'Hookshot': 0,
    'Great fairy\'s sword': 0,

    'Sword': 0,
    'Shield': 0,
    'Magic': 0,

    'Bottle red potion': 0,
    'Bottle gold dust': 0,
    'Bottle milk': 0,
    'Bottle chateau Romani': 0,
    'Bottle empty': 0,
    'Bottle empty 2': 0,
    'Seahorse': 0,

    'Postman\'s hat': 0,
    'All night mask': 0,
    'Blast mask': 0,
    'Stone mask': 0,
    'Great fairy mask': 0,
    'Deku mask': 0,
    'Keaton mask': 0,
    'Bremen mask': 0,
    'Bunny hood': 0,
    'Don Gero\'s mask': 0,
    'Mask of Scents': 0,
    'Goron mask': 0,
    'Romani\'s mask': 0,
    'Circus leaders\'s mask': 0,
    'Kafei\'s mask': 0,
    'Couple\'s mask': 0,
    'Mask of truth': 0,
    'Zora mask': 0,
    'Kamaro\'s mask': 0,
    'Gibdo\'s mask': 0,
    'Garo\'s mask': 0,
    'Captain\'s hat': 0,
    'Giant\'s mask': 0,
    'Fierce deity mask': 0,

    'Moon\'s tear': 0,
    'Land deed': 0,
    'Swamp deed': 0,
    'Mountain deed': 0,
    'Ocean deed': 0,
    'Room key': 0,
    'Letter for Kafei': 0,
    'Pendant of memories': 0,
    'Express mail': 0,
    'Bomber\'s notebook': 0,

    'Town fairy': 0,
    'WFT fairy': 0,
    'SHT fairy': 0,
    'GBT fairy': 0,
    'STT fairy': 0,
    'Swamp skulltula': 0,
    'Ocean skulltula': 0,

    'Odolwa\'s remains': 0,
    'Goht\'s remains': 0,
    'Gyorg\'s remains': 0,
    'Twinmold\'s remains': 0,

    'WFT small key': 0,
    'SHT small key': 0,
    'GBT small key': 0,
    'STT small key': 0,
    'WFT boss key': 0,
    'SHT boss key': 0,
    'GBT boss key': 0,
    'STT boss key': 0,

    'Temple of time': 0,
    'Song of healing': 0,
    'Epona\'s song': 0,
    'Song of soaring': 0,
    'Song of storms': 0,
    'Sonata of awakening': 0,
    'Goron lullaby': 0,
    'New wave bossa nova': 0,
    'Elegy of emptyness': 0,
    'Oath to order': 0
}